version: '3.1'

services:

  nginx:
    image: nginx
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - fastapi
      - rasa

  fastapi:
    build: ./fastapi-app
    container_name: fastapi_app
    ports:
      - 8000:8000
    volumes:
      - ./fastapi-app:/app
      - ./shared_data:/app/shared_data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      sql_db:
        condition: service_healthy
    command: sh -c "python main.py"

  rasa:
    build: ./rasa-app
    container_name: rasa_app
    ports:
      - 5005:5005
    volumes:
      - ./rasa-app:/app
      - ./shared_data:/app/shared_data   # Directorio compartido
    command: sh -c "rasa run -m models --enable-api --cors '*'"

  sql_db:
    image: postgres:15.2
    container_name: sql_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: chatbot
      TZ: America/Hermosillo
    volumes:
      - ./DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    environment:
      TZ: America/Hermosillo
    ports:
      - 8080:8080
    depends_on:
      sql_db:
        condition: service_started

volumes:
  shared_data:  # Nombre del volumen compartido